name: Daily Commit

on:
  schedule:
    - cron: "08 2 * * *"  # Runs daily at 02:08 UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Automated Commit by 21f1005206@ds.study.iitm.ac.in
        run: |
          echo "Updated on $(date)" >> daily_update.log
          git config --local user.email "21f1005206@ds.study.iitm.ac.in"
          git config --local user.name "github-actions[bot]"
          git add daily_update.log
          git commit -m "Automated daily commit [skip ci]" || exit 0
          git push
